from __future__ import annotations

from typing import Protocol, Sequence

from .conversation import AgentRun, Conversation, ConversationContext, ConversationMessage
from .models import AgentEvent


class ConversationRepository(Protocol):
    async def create_conversation(self, conversation: Conversation) -> None: ...
    async def get_conversation(self, conversation_id: str) -> Conversation | None: ...
    async def list_conversations(self) -> Sequence[Conversation]: ...
    async def add_message(self, message: ConversationMessage) -> None: ...
    async def list_messages(self, conversation_id: str) -> Sequence[ConversationMessage]: ...
    async def get_context(self, conversation_id: str) -> ConversationContext | None: ...
    async def upsert_context(self, context: ConversationContext) -> None: ...


class RunRepository(Protocol):
    async def create_run(self, run: AgentRun) -> None: ...
    async def get_run(self, run_id: str) -> AgentRun | None: ...
    async def list_runs(self, conversation_id: str) -> Sequence[AgentRun]: ...
    async def update_run(self, run: AgentRun) -> None: ...
    async def append_event(self, event: AgentEvent) -> None: ...
    async def list_events(self, run_id: str, after: int = 0) -> Sequence[AgentEvent]: ...
    async def wait_for_events(
        self, run_id: str, after: int, timeout_seconds: float
    ) -> Sequence[AgentEvent]: ...


class AgentRepository(ConversationRepository, RunRepository, Protocol):
    """Storage-neutral durable state Port implemented by SQLite in the MVP."""
