from __future__ import annotations

from typing import Protocol, Sequence

from .conversation import AgentRun, Conversation, ConversationContext, ConversationMessage
from .models import AgentEvent
from .task_graph import NodeAttempt, TaskGate, TaskGraph, TaskGraphSnapshot, TaskNode


class ActiveRunConflictError(RuntimeError):
    """Durable storage rejected a second active Run for one Conversation."""


class ConversationRepository(Protocol):
    async def create_conversation(self, conversation: Conversation) -> None: ...
    async def get_conversation(self, conversation_id: str) -> Conversation | None: ...
    async def list_conversations(self) -> Sequence[Conversation]: ...
    async def add_message(self, message: ConversationMessage) -> None: ...
    async def list_messages(self, conversation_id: str) -> Sequence[ConversationMessage]: ...
    async def get_context(self, conversation_id: str) -> ConversationContext | None: ...
    async def upsert_context(self, context: ConversationContext) -> None: ...


class RunRepository(Protocol):
    async def create_run(self, run: AgentRun) -> None: ...
    async def create_run_with_message(
        self, run: AgentRun, message: ConversationMessage
    ) -> None: ...
    async def get_run(self, run_id: str) -> AgentRun | None: ...
    async def list_runs(self, conversation_id: str) -> Sequence[AgentRun]: ...
    async def update_run(self, run: AgentRun) -> None: ...
    async def append_event(self, event: AgentEvent) -> AgentEvent: ...
    async def list_events(self, run_id: str, after: int = 0) -> Sequence[AgentEvent]: ...
    async def wait_for_events(
        self, run_id: str, after: int, timeout_seconds: float
    ) -> Sequence[AgentEvent]: ...
    async def list_recoverable_runs(self) -> Sequence[AgentRun]: ...
    async def get_trigger_message(self, run_id: str) -> ConversationMessage | None: ...
    async def register_runtime(self, runtime_id: str) -> None: ...
    async def heartbeat_runtime(self, runtime_id: str) -> None: ...
    async def unregister_runtime(self, runtime_id: str) -> None: ...
    async def prepare_recovery(self, runtime_id: str, stale_after_seconds: int) -> None: ...


class TaskGraphRepository(Protocol):
    async def create_task_graph(
        self, graph: TaskGraph, root_node: TaskNode, root_gate: TaskGate
    ) -> None: ...
    async def get_task_graph(self, run_id: str) -> TaskGraphSnapshot | None: ...
    async def update_task_graph(self, graph: TaskGraph) -> None: ...
    async def upsert_task_node(self, node: TaskNode) -> None: ...
    async def upsert_task_gate(self, gate: TaskGate) -> None: ...
    async def create_node_attempt(self, attempt: NodeAttempt) -> None: ...
    async def update_node_attempt(self, attempt: NodeAttempt) -> None: ...
    async def compare_and_swap_task_graph(
        self, graph: TaskGraph, expected_version: int
    ) -> bool: ...
    async def claim_task_node(
        self, node_id: str, lease_owner: str, lease_seconds: int
    ) -> NodeAttempt | None: ...
    async def commit_task_node(
        self, node: TaskNode, gate: TaskGate, attempt: NodeAttempt
    ) -> None: ...
    async def close_open_task_nodes(
        self, run_id: str, cancelled: bool, error_code: str
    ) -> None: ...


class AgentRepository(ConversationRepository, RunRepository, TaskGraphRepository, Protocol):
    """Storage-neutral durable state Port implemented by SQLite in the MVP."""
